#!/usr/bin/env python3
"""Generate ../internal/codebook/provoice.go: the bit order of the 142-bit
IMBE 7100x4400 (EDACS ProVoice) frame, from DSD's provoice_const.h (pW, pX;
ISC), and the parity-check masks of its [15,11] Hamming code from upstream
mbelib's ecc_const.h (imbe7100x4400hammingGenerator; ISC).  Run from research/."""
import os, re

ROOT = os.path.dirname(os.path.abspath(__file__))

def ints(path, name):
    src = open(path).read()
    i = src.index(name)
    body = re.sub(r'//[^\n]*', '', src[src.index('{', i) + 1:src.index('};', i)])
    return [int(x, 0) for x in re.findall(r'0x[0-9a-fA-F]+|-?\d+', body)]

dsd = os.path.join(ROOT, "..", "refs", "dsd-fme", "include", "provoice_const.h")
pW, pX = ints(dsd, "const int pW[142] ="), ints(dsd, "const int pX[142] =")
lens = [19, 24, 23, 23, 15, 15, 23]
assert sorted(zip(pW, pX)) == [(v, b) for v in range(7) for b in range(lens[v])], "pW/pX is not a permutation"
gen = ints(os.path.join(ROOT, "..", "refs", "mbelib", "ecc_const.h"), "imbe7100x4400hammingGenerator[4] =")
assert len(gen) == 4
# Parity bits 3..0 must be unit columns (a systematic code), and all 15
# columns distinct and non-zero (single errors correctable).
cols = [sum(((g >> p) & 1) << (3 - r) for r, g in enumerate(gen)) for p in range(15)]
assert [cols[3], cols[2], cols[1], cols[0]] == [8, 4, 2, 1], cols[:4]
assert len(set(cols)) == 15 and 0 not in cols

lines = [
    "// Code generated by research/tools/gen_provoice_tables.py from DSD's provoice_const.h",
    "// and mbelib's ecc_const.h (both ISC; see LICENSE.mbelib); DO NOT EDIT.",
    "",
    "package codebook",
    "",
    "// ProVoiceOrder[n] gives the code vector (c0..c6) and bit (0 = LSB) carried by",
    "// bit n of a 142-bit IMBE 7100x4400 (EDACS ProVoice) frame (DSD's pW, pX).",
    "var ProVoiceOrder = [142][2]int{",
    "\n".join("\t{%d, %d}," % (w, x) for w, x in zip(pW, pX)),
    "}",
    "",
    "// ProVoiceHamming are the parity-check masks of the ProVoice [15,11] Hamming",
    "// code over a codeword's bits 14..0 (data in 14..4); mask r ends in parity bit 3-r.",
    "var ProVoiceHamming = [4]uint32{" + ", ".join("0x%04x" % g for g in gen) + "}",
    "",
]
dst = os.path.join(ROOT, "..", "..", "internal", "codebook", "provoice.go")
open(dst, "w").write("\n".join(lines))
os.system(f"gofmt -w {dst}")
print("wrote", os.path.normpath(dst))
