#!/usr/bin/env python3
"""Extract the TIA-102.BABA (IMBE) windows and pitch LPF from the spec text
(Annex B: w_I, 301 pts; Annex C: w_R, 221 pts; Annex D: h_LPF, 21 taps;
Annex I: w_S, 211 pts) and emit
internal/imbe/windows.go (in the Go module, one level up).  Input: papers/BABA.txt (pdftotext -layout of the spec)."""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
txt = open(os.path.join(ROOT, "papers/BABA.txt")).read()


def section(start, end):
    i = txt.index(start)
    j = txt.index(end, i)
    return txt[i:j]


def pairs(sec):
    out = {}
    for line in sec.splitlines():
        toks = line.split()
        # rows are sequences of (n, value) pairs
        k = 0
        while k + 1 < len(toks):
            a, b = toks[k], toks[k + 1]
            if re.fullmatch(r"-?\d+", a) and re.fullmatch(r"-?\d*\.\d+", b):
                n = int(a)
                if n in out and abs(out[n] - float(b)) > 0:
                    raise SystemExit(f"conflicting value for n={n}")
                out[n] = float(b)
                k += 2
            else:
                k += 1
    return out


wI = pairs(section("Annex B Initial Pitch Estimation Window", "Annex C Pitch Re"))
wR = pairs(section("Annex C Pitch Re", "Annex D FIR Low Pass Filter"))
def ordered(sec, half):
    """Annex D rows are listed in order n = -half..half; the PDF text loses the
    minus sign on n = -1, so take the values by row order instead of label."""
    vals = [float(m.group(2)) for m in re.finditer(r"^\s*(-?\d+)\s+(-?\d*\.\d+)\s*$", sec, re.M)]
    assert len(vals) == 2 * half + 1, len(vals)
    return {n: v for n, v in zip(range(-half, half + 1), vals)}


h = ordered(section("Annex D FIR Low Pass Filter", "Annex E Gain Quantizer Levels"), 10)
wS = pairs(section("Annex I Speech Synthesis Window", "Annex J Log Magnitude"))
for name, d, half in (("wI", wI, 150), ("wR", wR, 110), ("hLPF", h, 10), ("wS", wS, 105)):
    assert sorted(d) == list(range(-half, half + 1)), (name, len(d), min(d), max(d))
    for n in range(1, half + 1):
        assert d[n] == d[-n], (name, n, d[n], d[-n])
    print(name, len(d), "points, symmetric, centre", d[0])
print("sum wI^2 =", sum(v * v for v in wI.values()), " sum hLPF =", sum(h.values()))


def emit(name, d, half, doc):
    vals = [d[n] for n in range(-half, half + 1)]
    lines = [f"// {doc}", f"var {name} = [{len(vals)}]float64{{"]
    for i in range(0, len(vals), 6):
        lines.append("\t" + ", ".join(repr(v) for v in vals[i:i + 6]) + ",")
    lines.append("}")
    return "\n".join(lines)


out = "\n".join([
    "// Code generated by research/tools/gen_imbe_windows.py from TIA-102.BABA Annexes B-D and I; DO NOT EDIT.",
    "",
    "// Package imbe holds the fixed windows of the TIA-102.BABA (IMBE) speech",
    "// analysis and synthesis, which the half-rate (AMBE+2 3600x2450) vocoder reuses.",
    "package imbe",
    "",
    emit("WI", wI, 150, "WI is the initial pitch estimation window w_I(n), n = -150..150 (Annex B), with Σ w_I² = 1."),
    "",
    emit("WR", wR, 110, "WR is the pitch refinement / spectral analysis window w_R(n), n = -110..110 (Annex C)."),
    "",
    emit("LPF", h, 10, "LPF is the 21-tap pitch-estimation lowpass h_LPF(n), n = -10..10 (Annex D)."),
    "",
    emit("WS", wS, 105, "WS is the speech synthesis window w_S(n), n = -105..105 (Annex I)."),
    "",
])
dst = os.path.join(ROOT, "..", "internal/imbe/windows.go")
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, "w").write(out)
print("wrote", dst)
