#!/usr/bin/env python3
"""Generate ../internal/codebook/tables.go (in the Go module) from mbelib's ambe3600x2450_const.h (ISC license).

  .venv/bin/python tools/gen_codebook.py
"""
import os

import mbelib_tables

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "..", "internal/codebook/tables.go")
T = mbelib_tables.load()


def flt(v):
    s = repr(float(v))
    return s


def emit_1d(name, arr, typ, doc):
    lines = [f"// {doc}", f"var {name} = [{len(arr)}]{typ}{{"]
    row = []
    for v in arr:
        row.append(flt(v) if typ == "float64" else str(int(v)))
        if len(row) == 8:
            lines.append("\t" + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("\t" + ", ".join(row) + ",")
    lines.append("}")
    return "\n".join(lines)


def emit_2d(name, arr, typ, doc):
    n, m = arr.shape
    lines = [f"// {doc}", f"var {name} = [{n}][{m}]{typ}{{"]
    for r in arr:
        vals = [flt(v) if typ == "float64" else str(int(v)) for v in r]
        lines.append("\t{" + ", ".join(vals) + "},")
    lines.append("}")
    return "\n".join(lines)


parts = [
    "// Code generated by research/tools/gen_codebook.py from mbelib's ambe3600x2450_const.h; DO NOT EDIT.",
    "//",
    "// The tables are the AMBE+2 3600x2450 (TIA-102.BABA half-rate) quantizer codebooks as",
    "// published in mbelib, Copyright (C) 2010 mbelib Author, used under the ISC license",
    "// reproduced in LICENSE.mbelib.",
    "",
    "package codebook",
    "",
    emit_1d("W0", T["AmbeW0table"], "float64",
            "W0[b0] is the fundamental frequency in cycles/sample for b0 = 0..119."),
    "",
    emit_1d("L", T["AmbeLtable"].astype(int), "int", "L[b0] is the number of harmonics for b0 = 0..119."),
    "",
    emit_2d("VUV", T["AmbeVuv"], "uint8",
            "VUV[b1][j] is the voicing decision (1 = voiced) for 500 Hz band j, per the published table."),
    "",
    emit_2d("BlockLen", T["AmbeLmprbl"], "int",
            "BlockLen[L] gives the four prediction-residual block lengths J1..J4 for L harmonics."),
    "",
    emit_1d("Dg", T["AmbeDg"], "float64", "Dg[b2] is the differential gain quantizer level."),
    "",
    emit_2d("PRBA24", T["AmbePRBA24"], "float64", "PRBA24[b3] holds PRBA vector elements G2..G4."),
    "",
    emit_2d("PRBA58", T["AmbePRBA58"], "float64", "PRBA58[b4] holds PRBA vector elements G5..G8."),
    "",
    emit_2d("HOC1", T["AmbeHOCb5"], "float64", "HOC1[b5] holds C1,3..C1,6."),
    "",
    emit_2d("HOC2", T["AmbeHOCb6"], "float64", "HOC2[b6] holds C2,3..C2,6."),
    "",
    emit_2d("HOC3", T["AmbeHOCb7"], "float64", "HOC3[b7] holds C3,3..C3,6."),
    "",
    emit_2d("HOC4", T["AmbeHOCb8"], "float64", "HOC4[b8] holds C4,3..C4,6."),
    "",
]
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(parts))
print("wrote", OUT)
