#!/usr/bin/env python3
"""Generate ../internal/codebook/dstar.go, the D-STAR AMBE 3600x2400
quantizer tables, from upstream mbelib's ambe3600x2400_const.h (ISC), and
the 72-bit frame interleave from DSD's dstar_const.h (dW, dX; ISC), which
mbelib-neo's dstar_frame.c reproduces exactly (checked when present).

mbelib reads b8 as three bits shifted left by one into its 16-row HOC table
(the low bit "forced to 0"), so only the even rows are reachable; they are
emitted as an 8-row table indexed by b8 directly.  The block lengths equal
the AMBE+2 ones and are not repeated.  Run from research/."""
import os, re, sys
import numpy as np

ROOT = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(ROOT, "..", "refs", "mbelib", "ambe3600x2400_const.h")).read()
T = {}
for m in re.finditer(r'const\s+(?:float|int)\s+(\w+)((?:\[\d+\])+)\s*=\s*\{(.*?)\};', src, re.S):
    body = re.sub(r'/\*.*?\*/', '', m.group(3), flags=re.S)
    body = re.sub(r'//[^\n]*', '', body)
    vals = [float(x) for x in re.findall(r'[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', body)]
    shape = [int(x) for x in re.findall(r'\[(\d+)\]', m.group(2))]
    assert int(np.prod(shape)) == len(vals), (m.group(1), shape, len(vals))
    T[m.group(1)] = np.array(vals).reshape(shape)

sys.path.insert(0, ROOT)
import mbelib_tables
A = mbelib_tables.load()
assert np.array_equal(T["AmbePlusLmprbl"], A["AmbeLmprbl"]), "D-STAR block lengths differ from AMBE+2"
L = T["AmbePlusLtable"].astype(int)
assert all(L[120:] == 56), "Ltable padding changed"

def ints(src, name):
    i = src.index(name)
    body = re.sub(r'//[^\n]*', '', src[src.index('{', i) + 1:src.index('};', i)])
    return [int(x) for x in re.findall(r'-?\d+', body)]

dsd = open(os.path.join(ROOT, "..", "refs", "dsd-fme", "include", "dstar_const.h")).read()
dW, dX = ints(dsd, "const int dW[72] ="), ints(dsd, "const int dX[72] =")
lens = [24, 23, 11, 14]
assert sorted(zip(dW, dX)) == [(v, b) for v in range(4) for b in range(lens[v])], "dW/dX not a permutation"
neo = os.path.join(ROOT, "..", "refs", "mbelib-neo", "src", "ambe", "dstar_frame.c")
if os.path.exists(neo):
    n = open(neo).read()
    assert (ints(n, "dstar_dW[72]"), ints(n, "dstar_dX[72]")) == (dW, dX), "mbelib-neo's interleave differs from DSD's"
    print("interleave: DSD's dW/dX equal mbelib-neo's")

def flt(v): return repr(float(v))

def rows(name, arr, typ, doc):
    n, m = arr.shape
    out = [f"// {doc}", f"var {name} = [{n}][{m}]{typ}{{"]
    for r in arr:
        out.append("\t{" + ", ".join(flt(v) if typ == "float64" else str(int(v)) for v in r) + "},")
    return "\n".join(out + ["}"])

def flat(name, arr, typ, doc, per=8):
    out = [f"// {doc}", f"var {name} = [{len(arr)}]{typ}{{"]
    for i in range(0, len(arr), per):
        out.append("\t" + ", ".join(flt(v) if typ == "float64" else str(int(v)) for v in arr[i:i + per]) + ",")
    return "\n".join(out + ["}"])

parts = [
    "// Code generated by research/tools/gen_dstar_codebook.py from mbelib and DSD; DO NOT EDIT.",
    "//",
    "// The quantizer codebooks are D-STAR's AMBE 3600x2400 tables as published in",
    "// mbelib's ambe3600x2400_const.h, Copyright (C) 2010 mbelib Author, and the",
    "// frame interleave is DSD's dstar_const.h (dW, dX), Copyright (C) 2010 DSD",
    "// Author; both are used under the ISC license (LICENSE.mbelib, LICENSE.dsd).",
    "",
    "package codebook",
    "",
    flat("DStarL", L[:120], "int", "DStarL[b0] is the number of harmonics for b0 = 0..119."),
    "",
    rows("DStarVUV", T["AmbePlusVuv"], "uint8", "DStarVUV[b1][j] is the voicing decision (1 = voiced) for 500 Hz band j."),
    "",
    flat("DStarDg", T["AmbePlusDg"], "float64", "DStarDg[b2] is the differential gain quantizer level."),
    "",
    rows("DStarPRBA24", T["AmbePlusPRBA24"], "float64", "DStarPRBA24[b3] holds PRBA vector elements G2..G4."),
    "",
    rows("DStarPRBA58", T["AmbePlusPRBA58"], "float64", "DStarPRBA58[b4] holds PRBA vector elements G5..G8."),
    "",
    rows("DStarHOC1", T["AmbePlusHOCb5"], "float64", "DStarHOC1[b5] holds C1,3..C1,6."),
    "",
    rows("DStarHOC2", T["AmbePlusHOCb6"], "float64", "DStarHOC2[b6] holds C2,3..C2,6."),
    "",
    rows("DStarHOC3", T["AmbePlusHOCb7"], "float64", "DStarHOC3[b7] holds C3,3..C3,6."),
    "",
    rows("DStarHOC4", T["AmbePlusHOCb8"][0::2], "float64", "DStarHOC4[b8] holds C4,3..C4,6 (the even rows of mbelib's table)."),
    "",
    "// DStarInterleave[i] gives the code vector (c0..c3) and bit (0 = LSB) carried by",
    "// bit i of the 72-bit D-STAR voice frame (DSD's dW, dX).",
    "var DStarInterleave = [72][2]int{",
    "\n".join("\t{%d, %d}," % (w, x) for w, x in zip(dW, dX)),
    "}",
    "",
]
dst = os.path.join(ROOT, "..", "..", "internal", "codebook", "dstar.go")
open(dst, "w").write("\n".join(parts))
os.system(f"gofmt -w {dst}")
print("wrote", os.path.normpath(dst))
